version: '3.8'

services:
  retro-aim-server:
    build: .
    ports:
      - "5190:5190"
      - "5191:5191"
      - "5192:5192"
      - "5193:5193"
      - "5194:5194"
      - "5195:5195"
      - "5196:5196"
      - "5197:5197"
      - "8080:8080"
    volumes:
      - ./config/settings.env:/app/config/settings.env
    environment:
      - OSCAR_HOST=0.0.0.0
